### ISSUE TITLE
Where's the code, dude?

### ISSUE THREAD

**Issue by alxfed** [Victorwz/LongMem#2]
Links in the article https://aka.ms/LongMem and on the arxive page lead to this empty repo. 
Congratulations with your 'publication'!

**Comment by otto-dev** [comment]
> Links in the article https://aka.ms/LongMem and on the arxive page lead to this empty repo. Congratulations with your 'publication'!

This just shows that a Ph.D. in Mathematics can't teach anyone basic manners or common sense.

Having said that, I'm also looking forward to the release of the code, if the researchers are so kind to share it. The paper was released today, so I'll come back later.

**Comment by Victorwz** [comment]
Hi you all, apology for releasing the code a little bit late due to personal issues. I will immediately organize the documentation for easier reproduction and discussion.

**Comment by EwoutH** [comment]
@Victorwz Don't apologize, this looks like amazing work and it's great that you have published the code open-source so that your paper is reproducible and allow others to build upon it. Thanks!

Like Otto rightfully said, Alex is the one who should apologize here.

**Comment by alxfed** [comment]
Thank you, Victor.
