### ISSUE TITLE
About dataset used in training and evaluation and model checkpoints

### ISSUE THREAD

**Issue by JF-D** [Victorwz/LongMem#7]
Hi, LongMem is an awesome work. I have the following questions
1. are you going to release the scripts you used to collect the training and evaluation dataset or the dataset itself?
2. are you going to release the a trained checkpoints?

Thanks!

**Comment by Victorwz** [comment]
Thanks for your interest in our work. The answers to both questions are yes, we will release the training/eval scripts and pre-trained checkpoints in one week. Additionally, we plan to release the preprocessing script for the Pile training corpus.

**Comment by JF-D** [comment]
Great! Looking forward to your updates!
